name: nf-crispriseq

channels:
    - conda-forge
    - bioconda

dependencies:
    - python=3.11
    - pip
    - bioconda::fastqc
    - bioconda::seqtk
    - bioconda::sra-tools
    - pip:
        - "git+https://github.com/scbirlab/crispio.git@fitness#egg=crispio[fit_cuda_local]"
        - 'carabiner-tools[mpl,pd]==0.0.3.post1'
        - 'cutadapt==5.0'
        - 'multiqc==1.21'
        - 'umi-tools==1.1.6'